version: '3'

services:
  db_init:
    image: icees-db-init
    container_name: ${ICEES_API_INSTANCE_NAME}-db-init
    build:
      context: .
    env_file:
      - .env
    environment:
      - ICEES_DB=sqlite
      - DATA_PATH=/data
      - DB_PATH=/db
    volumes:
      - $DATA_PATH:/data
      - $DB_PATH:/db
      - $CONFIG_PATH:/config
