[package]
name = "precompute"
version = "0.1.0"  #:version
authors = ["Patrick Wang <patrickkwang@users.noreply.github.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
statrs = "0.15.0"
