apiVersion: v1
kind: Pod 
metadata:
  name: iceesdb-service
spec:
  containers:
    - image: renci/icees-db-init:1.0
      name: icees-db-init
      env:
        - name: INPUT_FEATURE_FILE_WITH_PATH
          value: "/iceesdata/covid/config/features.yml"
        - name: OUTPUT_VALUE_SETS_FILE_WITH_PATH
          value: "/iceesdata/covid/config/value_sets.yml"
        - name: ICEES_DB
          value: "sqlite"
        - name: DB_PATH
          value: "/iceesdata/covid/sqlite"
        - name: DATA_PATH
          value: "/iceesdata/covid/data"
        - name: CONFIG_PATH
          value: "/iceesdata/covid/config"      
      volumeMounts:
        - name: iceesdata
          mountPath: /iceesdata
      resources:
        requests:
          cpu: "1"
          memory: 8Gi
        limits:
          memory: "10Gi"
          cpu: "2" 
  restartPolicy: Never        
  volumes:
    - name: iceesdata
      persistentVolumeClaim:
        claimName: iceesdata
            
